---
openjre_package: '{%- if java_version == "latest" and ansible_distribution_version|int >= 11 -%}
                     jre-8
                  {%- elif java_version == "latest" and ansible_distribution_version|int == 10 -%}
                     CSWjre
                  {%- elif ansible_distribution_version|int == 10 -%}
                     CSWjre{{ java_version }}
                  {%- else -%}
                     jre-{{ java_version }}
                  {%- endif -%}'

openjdk_package: '{%- if java_version == "latest" and ansible_distribution_version|int >= 11 -%}
                     jdk-8
                  {%- elif java_version == "latest" and ansible_distribution_version|int == 10 -%}
                     CSWjdk
                  {%- elif ansible_distribution_version|int == 10 -%}
                     CSWjdk{{ java_version }}
                  {%- else -%}
                     jdk-{{ java_version }}
                  {%- endif -%}'
