---

#- name: "\e[30;48;5;214minstall and start Tomcat-9\e[0m"

- name: "\e[30;48;5;214mCreate App zfs pool\e[0m"
  zfs:
    name: rpool/www
    state: present
    extra_zfs_properties: 
      snapdir: visible

- name: "\e[30;48;5;214mAdd group tomcat\e[0m"
  group:
    name: tomcat
    state: present

- name: "\e[30;48;5;214mAdd user tomcat\e[0m"
  user:
    name: tomcat
    group: tomcat
    comment: User for run tomcat
    home: "{{ tomcat_base_dir|default('/opt/tomcat') }}"
    createhome: no
  become: true

- name: "\e[30;48;5;214mDownload & Extract Tomacat\e[0m"
  unarchive:
    src: http://apache.ip-connect.vn.ua/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.zip
    dest: /opt
    owner: tomcat
    group: tomcat
    mode: '0755'
    remote_src: yes

- name: "\e[30;48;5;214mCreate symlinks\e[0m"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: '/opt/apache-tomcat-9.0.27', dest: "{{ tomcat_base_dir|default('/opt/tomcat') }}" }
    - { src: "{{ tomcat_base_dir|default('/opt/tomcat') }}/logs", dest: '/var/log/tomcat' }
    - { src: '/rpool/www', dest: "{{ tomcat_base_dir|default('/opt/tomcat') }}/webapp" }

- name: "\e[30;48;5;214mCopy tomcat.xml\e[0m"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  with_items:
    - { src: 'tomcat9.xml', dest: '/var/svc/manifest/site/tomcat9.xml' }

- name: "\e[30;48;5;214mSet files permission\e[0m"
  file:
    dest: "{{ tomcat_base_dir|default('/opt/tomcat/') }}/bin"
    owner: tomcat
    group: tomcat
    mode: '0755'
    recurse: yes

- name: "\e[30;48;5;214mRegister service on {{ http_port }}\e[0m"
  command: "{{ item.command }}"
  with_items:
    - { command: 'svccfg import /var/svc/manifest/site/tomcat9.xml' }
    - { command: 'svcadm restart svc:/system/manifest-import' }
  environment: 
    CATALINA_BASE: "{{ tomcat_base_dir|default('/opt/tomcat') }}"

- name: "\e[30;48;5;214mDeploy config\e[0m"
  template:
    src: templates/server.j2
    dest: /opt/tomcat/conf/server.xml
    owner: tomcat
    group: tomcat
    mode: '0644'
#    backup: yes
  notify: restart tomcat

