- name: Create myid (cluster mode only)
  ansible.builtin.copy:
    dest: "{{ zookeeper_data }}/myid"
    content: "{{ item.0 + 1 }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0644'
  with_indexed_items: "{{ zookeeper_nodes }}"
  when: zookeeper_mode == "cluster" and item.1 == inventory_hostname

- name: Generate conf file Zookeeper
  ansible.builtin.template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_conf }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: '0644'
  notify: Restart Zookeeper
