---
- name: Validate zookeeper_nodes for cluster mode
  ansible.builtin.assert:
    that:
      - zookeeper_nodes is defined
      - zookeeper_nodes | length > 2
    fail_msg: "zookeeper_nodes must be defined and have at least tree nodes in cluster mode"
  when: zookeeper_mode == "cluster"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - tar
    - gzip
    - unzip
    - openjdk-8-jre
