- name: Ensure Zookeeper is running
  ansible.builtin.systemd:
    name: zookeeper
    state: started
    enabled: yes
  notify: Start Zookeeper

- name: Zookeeper self-health check
  ansible.builtin.wait_for:
    port: "{{ zookeeper_client_port }}"
    timeout: 5
    retries: 5
    delay: 3
